# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get -qq update
  - sed -i '/tests/d' ./.Rbuildignore
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
